### ISSUE TITLE
Create text post on front end

### ISSUE THREAD

**Issue by rrdelaney** [SuperFeed/SuperFeed#11]
_From @rrdelaney on March 21, 2016 18:47_

Functionality to create a test post on the front end

_Copied from original issue: SuperFeed/Front#10_

**Comment by Cdower** [comment]
it won't let me assign this to myself

**Comment by GregWeil** [comment]
I'm doing the client action, Chris is doing the component

**Comment by rrdelaney** [comment]
I fixed this when fixing the CORS issue encountered on this weekend. It was a simple post request, but styling still needs to happen.
