### ISSUE TITLE
Create image post on front end

### ISSUE THREAD

**Issue by rrdelaney** [SuperFeed/SuperFeed#12]
_From @rrdelaney on March 21, 2016 18:48_

Should be able to attach an image to a post when creating on the front end

_Copied from original issue: SuperFeed/Front#11_

**Comment by Cdower** [comment]
I'll have this done soon

**Comment by rrdelaney** [comment]
Any update on this?

**Comment by Cdower** [comment]
yeah, I put in the upload part.  I want to double check that everything gets written to the db, then I think I need to make posts display the images but I I'm pretty sure that I know what to do for that .

**Comment by Cdower** [comment]
successfully writing the images to DB.  I just need to edit post.jsx to  display the images from the DB.

**Comment by rrdelaney** [comment]
Closed by #48
