### ISSUE TITLE
Import data from Twitter

### ISSUE THREAD

**Issue by rrdelaney** [SuperFeed/SuperFeed#16]
_From @rrdelaney on March 21, 2016 18:55_

Posts should be imported from location with Twitter

_Copied from original issue: SuperFeed/Front#15_

**Comment by Cdower** [comment]
I can take care of this one

**Comment by rrdelaney** [comment]
Could you try to pick something in the current sprint?

See https://github.com/SuperFeed/SuperFeed/milestones

**Comment by Cdower** [comment]
Yes, I can and will do that. I didn't see the milestones page before, only the issues page. I'll look at today.
