### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by rrdelaney** [SuperFeed/SuperFeed#36]
Need a logo for the project. Should have a favicon too.

**Comment by luxuc** [comment]
I can help to make a logo and a favicon

**Comment by rrdelaney** [comment]
It would be more useful if you could work on something in the current [milestone](https://github.com/SuperFeed/SuperFeed/milestones/Version%200.2)

**Comment by luxuc** [comment]
I could try to work on the like post part

**Comment by rrdelaney** [comment]
Done. See commit fd2df69
